### ISSUE TITLE
watch mode ignores file changes

### ISSUE THREAD

**Issue by FND** [faucet-pipeline/faucet-pipeline-static#32]
false alarm: I had misconfigured `watchDirs` 😳 

----

```javascript
    static: [{
        source: "./assets",
        target: "./dist"
    }]
```
```javascript
    static: [{
        source: "./assets/lipsum.txt",
        target: "./dist/lipsum.txt"
    }]
```

with either of those confgurations (i.e. both directory and file references), after successfully copying `./assets/lipsum.txt` on startup (`faucet --watch`), subsequent changes to that file do _not_ result in it being copied anew

**Comment by moonglum** [comment]
😶
